image: node:latest

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline


build_dev:
  stage: build
  script:
    - npm run build
    - echo "Building the app"
  artifacts:
    name: '$CI_JOB_NAME'
    paths:
      - dist
  only:
    - development


build_prod:
  stage: build
  script:
    - npm run buildProd
    - echo "Building the app"
  artifacts:
    name: '$CI_JOB_NAME'
    paths:
      - dist
  only:
    - master

deploy_dev:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 sync ./dist s3://dev.artemwolynski.com/ --acl=public-read --delete
      - aws cloudfront create-invalidation --distribution-id $STAGE_CLOUDFRONT_DIST --paths "/*"
  only:
    - development

deploy_prod:
  image: python:latest
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 sync ./dist s3://artemwolynski.com/ --acl=public-read --delete
      - aws cloudfront create-invalidation --distribution-id $PROD_CLOUDFRONT_DIST --paths "/*"
  only:
    - master
  when: manual
